# Generated by Django 5.2.9 on 2026-01-09

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="percent_off",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="amount_off_net_eur",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="apply_on_discounted_items",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coupon",
            name="free_shipping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coupon",
            name="free_shipping_methods",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
