# Generated by Django 5.2.9 on 2026-01-09

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0016_orderdiscount"),
        ("promotions", "0002_coupon_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="usage_limit_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="usage_limit_per_user",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="times_redeemed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="redemptions",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="coupon_redemption",
                        to="checkout.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="coupon_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["coupon", "user"], name="promotions__coupon__d4c2f9_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["coupon", "-created_at"], name="promotions__coupon__3d9b55_idx"),
        ),
        migrations.AddConstraint(
            model_name="couponredemption",
            constraint=models.UniqueConstraint(fields=("coupon", "order"), name="uniq_coupon_redemption_coupon_order"),
        ),
    ]
