# Generated by Django 5.2.9 on 2026-01-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0003_coupon_limits_and_redemptions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="couponredemption",
            new_name="promotions__coupon__00bce9_idx",
            old_name="promotions__coupon__d4c2f9_idx",
        ),
        migrations.RenameIndex(
            model_name="couponredemption",
            new_name="promotions__coupon__a65f9e_idx",
            old_name="promotions__coupon__3d9b55_idx",
        ),
    ]
