# Generated by Django 5.2.9 on 2026-01-09

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0015_inventoryitem_never_discount"),
        ("promotions", "0004_rename_promotions__coupon__d4c2f9_idx_promotions__coupon__00bce9_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="Higher wins"),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allowed_channels",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "percent_off",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "amount_off_net_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("category", "Category"),
                            ("brand", "Brand"),
                            ("product", "Product"),
                            ("variant", "Variant"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="promo_rules",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="promo_rules",
                        to="catalog.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="promo_rules",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="promo_rules",
                        to="catalog.variant",
                    ),
                ),
                (
                    "customer_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If empty, applies to all customers. If set, applies only to users in these groups.",
                        related_name="promo_rules",
                        to="accounts.customergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="promorule",
            index=models.Index(fields=["is_active", "-priority"], name="promotions__is_acti_3d9e5e_idx"),
        ),
        migrations.AddIndex(
            model_name="promorule",
            index=models.Index(fields=["scope", "is_active"], name="promotions__scope__e9cc8f_idx"),
        ),
    ]
