# Generated by Django 5.2.9 on 2026-01-09

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    SalesChannel = apps.get_model("promotions", "SalesChannel")
    PromoRule = apps.get_model("promotions", "PromoRule")
    PromoRuleConditionGroup = apps.get_model("promotions", "PromoRuleConditionGroup")
    PromoRuleCondition = apps.get_model("promotions", "PromoRuleCondition")
    Coupon = apps.get_model("promotions", "Coupon")

    ShippingMethod = apps.get_model("shipping", "ShippingMethod")

    # Seed default channels
    defaults = [
        {"code": "normal", "name": "Normal", "sort_order": 0, "is_active": True},
        {"code": "outlet", "name": "Outlet", "sort_order": 10, "is_active": True},
    ]
    for d in defaults:
        SalesChannel.objects.get_or_create(code=d["code"], defaults=d)

    channel_by_code = {c.code: c for c in SalesChannel.objects.all()}

    # Migrate PromoRule.allowed_channels_json -> PromoRule.channels
    for r in PromoRule.objects.all().iterator():
        codes = [str(x).strip().lower() for x in (getattr(r, "allowed_channels_json", None) or []) if str(x).strip()]
        if codes:
            r.channels.set([channel_by_code[c] for c in codes if c in channel_by_code])
        else:
            # empty means all channels -> keep M2M empty
            pass

        # Migrate legacy scope fields -> condition groups
        # Create a single default group if none exist.
        if not PromoRuleConditionGroup.objects.filter(promo_rule_id=r.id).exists():
            g = PromoRuleConditionGroup.objects.create(promo_rule_id=r.id, name="", sort_order=0)

            scope = getattr(r, "scope", "all")
            if scope == "category" and getattr(r, "category_id", None):
                PromoRuleCondition.objects.create(group_id=g.id, kind="category", category_id=r.category_id)
            elif scope == "brand" and getattr(r, "brand_id", None):
                PromoRuleCondition.objects.create(group_id=g.id, kind="brand", brand_id=r.brand_id)
            elif scope == "product" and getattr(r, "product_id", None):
                PromoRuleCondition.objects.create(group_id=g.id, kind="product", product_id=r.product_id)
            elif scope == "variant" and getattr(r, "variant_id", None):
                PromoRuleCondition.objects.create(group_id=g.id, kind="variant", variant_id=r.variant_id)
            else:
                # scope=all or missing target -> empty group => matches all
                pass

    # Migrate Coupon.free_shipping_methods_json -> Coupon.free_shipping_methods (M2M)
    sm_by_code = {m.code: m for m in ShippingMethod.objects.all()}
    for c in Coupon.objects.all().iterator():
        codes = [str(x).strip() for x in (getattr(c, "free_shipping_methods_json", None) or []) if str(x).strip()]
        if not codes:
            continue
        c.free_shipping_methods.set([sm_by_code[x] for x in codes if x in sm_by_code])


def backwards(apps, schema_editor):
    # Keep backward migration minimal: leave data as-is.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0003_add_lpexpress_courier"),
        ("promotions", "0005_promorule"),
        ("catalog", "0015_inventoryitem_never_discount"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "code"]},
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="free_shipping_methods",
            new_name="free_shipping_methods_json",
        ),
        migrations.AddField(
            model_name="coupon",
            name="free_shipping_methods",
            field=models.ManyToManyField(
                blank=True,
                help_text="If empty and free_shipping=true, free shipping applies to all methods.",
                related_name="coupons_free_shipping",
                to="shipping.shippingmethod",
            ),
        ),
        migrations.RenameField(
            model_name="promorule",
            old_name="allowed_channels",
            new_name="allowed_channels_json",
        ),
        migrations.AddField(
            model_name="promorule",
            name="channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="If empty, applies to all channels.",
                related_name="promo_rules",
                to="promotions.saleschannel",
            ),
        ),
        migrations.CreateModel(
            name="PromoRuleConditionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "promo_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_groups",
                        to="promotions.promorule",
                    ),
                ),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="PromoRuleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("category", "Category"),
                            ("brand", "Brand"),
                            ("product", "Product"),
                            ("variant", "Variant"),
                            ("product_group", "Product group"),
                            ("feature_value", "Feature value"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_rule_conditions",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_rule_conditions",
                        to="catalog.category",
                    ),
                ),
                (
                    "feature_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_rule_conditions",
                        to="catalog.featurevalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_rule_conditions",
                        to="catalog.product",
                    ),
                ),
                (
                    "product_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_rule_conditions",
                        to="catalog.productgroup",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_rule_conditions",
                        to="catalog.variant",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="promotions.promoruleconditiongroup",
                    ),
                ),
            ],
            options={"ordering": ["id"], "indexes": [models.Index(fields=["kind"], name="promotions__kind__bfe7e3_idx")]},
        ),
        migrations.RunPython(forwards, backwards),
    ]
