# Generated by Django 5.2.9 on 2026-01-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0006_conditions_channels_and_shipping_m2m"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="promorule",
            new_name="promotions__is_acti_a80be6_idx",
            old_name="promotions__is_acti_3d9e5e_idx",
        ),
        migrations.RenameIndex(
            model_name="promorule",
            new_name="promotions__scope_3ed3b6_idx",
            old_name="promotions__scope__e9cc8f_idx",
        ),
        migrations.RenameIndex(
            model_name="promorulecondition",
            new_name="promotions__kind_30fd11_idx",
            old_name="promotions__kind__bfe7e3_idx",
        ),
    ]
