# Generated by Django 5.2.9 on 2026-01-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0008_site_scope"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="promorule",
            new_name="promotions__site_id_e8729e_idx",
            old_name="promotions__site_acti_pri_idx",
        ),
    ]
