# Generated by Django 5.2.9 on 2026-01-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("gateway", "Gateway"),
                            ("cod", "Cash on delivery"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("instructions", models.TextField(blank=True, default="")),
                (
                    "bank_account_iban",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "bank_account_bic",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "bank_account_beneficiary",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "bank_account_bank_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "bank_account_purpose_template",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "country_code", "sort_order"],
                        name="payments_pa_is_acti_a6fbbb_idx",
                    ),
                    models.Index(
                        fields=["code", "is_active"], name="payments_pa_code_2347b1_idx"
                    ),
                ],
            },
        ),
    ]
