# Generated by Django 5.2.9 on 2026-01-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NeopayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("project_id", models.BigIntegerField()),
                ("project_key", models.CharField(max_length=255)),
                ("enable_bank_preselect", models.BooleanField(default=False)),
                ("client_redirect_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="payments_ne_is_acti_d69212_idx",
                    )
                ],
            },
        ),
    ]
