# Generated by Django 5.2.9 on 2026-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_neopayconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neopayconfig",
            name="client_redirect_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
