# Generated by Django 5.2.9 on 2026-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_neopayconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="neopayconfig",
            name="banks_api_base_url",
            field=models.URLField(blank=True, default="https://psd2.neopay.lt/api"),
        ),
        migrations.AddField(
            model_name="neopayconfig",
            name="enable_bank_preselect",
            field=models.BooleanField(default=False),
        ),
    ]
