# Generated by Django 5.2.9 on 2026-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_neopayconfig_banks_api_base_url_and_more"),
    ]

    operations = [
    ]
