# Generated by Django 5.2.9 on 2026-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_neopayconfig_banks_api_base_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="neopayconfig",
            name="force_bank_bic",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="neopayconfig",
            name="force_bank_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
