# Generated by Django 5.2.9 on 2026-01-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_neopaybank"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="neopaybank",
            new_name="payments_ne_country_ccef0c_idx",
            old_name="payments_neop_country__96a492_idx",
        ),
        migrations.RenameIndex(
            model_name="neopaybank",
            new_name="payments_ne_bic_08139d_idx",
            old_name="payments_neop_bic_2ed0bd_idx",
        ),
    ]
