# Generated by Django 5.2.9 on 2026-01-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0007_rename_payments_neop_country__96a492_idx_payments_ne_country_ccef0c_idx_and_more",
        ),
    ]

    operations = [
    ]
