# Generated by Django 5.2.9 on 2026-01-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_recently_viewed_product"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="analytics_a_name_119f75_idx",
            old_name="analytics_an_name_3a9193_idx",
        ),
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="analytics_a_user_id_e40ca1_idx",
            old_name="analytics_an_user_i_60f6cc_idx",
        ),
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="analytics_a_visitor_a13bd3_idx",
            old_name="analytics_an_visito_62c9b1_idx",
        ),
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="analytics_a_object__f7c1f4_idx",
            old_name="analytics_an_object_59840b_idx",
        ),
        migrations.RenameIndex(
            model_name="analyticsoutbox",
            new_name="analytics_a_provide_0b628b_idx",
            old_name="analytics_an_provid_a5a60c_idx",
        ),
        migrations.RenameIndex(
            model_name="recentlyviewedproduct",
            new_name="analytics_r_user_id_078de6_idx",
            old_name="analytics_r_user_id_5b7cb1_idx",
        ),
        migrations.RenameIndex(
            model_name="recentlyviewedproduct",
            new_name="analytics_r_visitor_4379b2_idx",
            old_name="analytics_r_visito_496f5c_idx",
        ),
        migrations.RenameIndex(
            model_name="recentlyviewedproduct",
            new_name="analytics_r_product_640b09_idx",
            old_name="analytics_r_product_6f7731_idx",
        ),
        migrations.RenameIndex(
            model_name="visitorlink",
            new_name="analytics_v_visitor_09359a_idx",
            old_name="analytics_vi_visito_21d4f5_idx",
        ),
    ]
