# Generated by Django 5.2.9 on 2026-01-14

from django.db import migrations, models
import django.db.models.deletion


def _default_site_id(apps) -> int | None:
    Site = apps.get_model("api", "Site")
    s = Site.objects.filter(is_active=True, code="default").only("id").first()
    if s is None:
        s = Site.objects.filter(is_active=True).only("id").order_by("code").first()
    if s is None:
        return None
    return int(s.id)


def backfill_site_ids(apps, schema_editor):
    sid = _default_site_id(apps)
    if sid is None:
        return

    AnalyticsEvent = apps.get_model("analytics", "AnalyticsEvent")
    VisitorLink = apps.get_model("analytics", "VisitorLink")
    RecentlyViewedProduct = apps.get_model("analytics", "RecentlyViewedProduct")

    AnalyticsEvent.objects.filter(site_id__isnull=True).update(site_id=sid)
    VisitorLink.objects.filter(site_id__isnull=True).update(site_id=sid)
    RecentlyViewedProduct.objects.filter(site_id__isnull=True).update(site_id=sid)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_siteconfig_neopay_and_legal"),
        ("analytics", "0003_rename_analytics_an_name_3a9193_idx_analytics_a_name_119f75_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytics_events",
                to="api.site",
            ),
        ),
        migrations.AddField(
            model_name="visitorlink",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="visitor_links",
                to="api.site",
            ),
        ),
        migrations.AddField(
            model_name="recentlyviewedproduct",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recently_viewed_products",
                to="api.site",
            ),
        ),
        migrations.RunPython(code=backfill_site_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="analyticsevent",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytics_events",
                to="api.site",
            ),
        ),
        migrations.AlterField(
            model_name="visitorlink",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="visitor_links",
                to="api.site",
            ),
        ),
        migrations.AlterField(
            model_name="recentlyviewedproduct",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recently_viewed_products",
                to="api.site",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visitorlink",
            unique_together={("site", "user", "visitor_id")},
        ),
        migrations.RemoveConstraint(
            model_name="recentlyviewedproduct",
            name="analytics_rvp_unique_user_product",
        ),
        migrations.RemoveConstraint(
            model_name="recentlyviewedproduct",
            name="analytics_rvp_unique_visitor_product",
        ),
        migrations.AddConstraint(
            model_name="recentlyviewedproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("site", "user", "product"),
                name="analytics_rvp_unique_user_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="recentlyviewedproduct",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("visitor_id", "")),
                fields=("site", "visitor_id", "product"),
                name="analytics_rvp_unique_visitor_product",
            ),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(fields=["site", "user", "last_viewed_at"], name="analytics_r_site_user_lv_idx"),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(fields=["site", "visitor_id", "last_viewed_at"], name="analytics_r_site_vid_lv_idx"),
        ),
    ]
