# Generated by Django 5.2.9 on 2026-01-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_site_scope"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recentlyviewedproduct",
            name="analytics_r_user_id_078de6_idx",
        ),
        migrations.RemoveIndex(
            model_name="recentlyviewedproduct",
            name="analytics_r_visitor_4379b2_idx",
        ),
        migrations.RenameIndex(
            model_name="recentlyviewedproduct",
            new_name="analytics_r_site_id_ff777c_idx",
            old_name="analytics_r_site_user_lv_idx",
        ),
        migrations.RenameIndex(
            model_name="recentlyviewedproduct",
            new_name="analytics_r_site_id_2a0f09_idx",
            old_name="analytics_r_site_vid_lv_idx",
        ),
    ]
