# Generated by Django 5.2.9 on 2026-01-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_favorite_product"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="favoriteproduct",
            new_name="analytics_f_site_id_a453bb_idx",
            old_name="analytics_fa_site_id_4a3ab6_idx",
        ),
        migrations.RenameIndex(
            model_name="favoriteproduct",
            new_name="analytics_f_site_id_78ff5e_idx",
            old_name="analytics_fa_site_id_2f3b73_idx",
        ),
        migrations.RenameIndex(
            model_name="favoriteproduct",
            new_name="analytics_f_product_3ecd7f_idx",
            old_name="analytics_fa_product_id_1df62d_idx",
        ),
    ]
