# Generated by Django 5.2.9 on 2026-01-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DpdLocker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locker_id", models.CharField(max_length=80, unique=True)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("street", models.CharField(blank=True, default="", max_length=255)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["country_code", "city", "name", "locker_id"],
                "indexes": [
                    models.Index(
                        fields=["country_code", "city"],
                        name="dpd_dpdlock_country_ed22c5_idx",
                    ),
                    models.Index(
                        fields=["locker_id"], name="dpd_dpdlock_locker__20811a_idx"
                    ),
                ],
            },
        ),
    ]
