# Generated by Django 5.2.9 on 2026-01-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_remove_cmspagetranslation_layout"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cmspagetranslation",
            new_name="cms_cmspage_cms_pag_b83cf0_idx",
            old_name="cms_cmspag_cms_pag_77e9c7_idx",
        ),
    ]
