# Generated by Django 5.2.9 on 2026-01-14

import django.db.models.deletion
from django.db import migrations, models


def backfill_cms_page_site(apps, schema_editor):
    Site = apps.get_model("api", "Site")
    CmsPage = apps.get_model("cms", "CmsPage")

    site = Site.objects.filter(is_active=True, code="default").only("id").first()
    if site is None:
        site = Site.objects.filter(is_active=True).only("id").order_by("code").first()
    if site is None:
        return

    CmsPage.objects.filter(site__isnull=True).update(site_id=int(site.id))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("cms", "0005_rename_cms_cmspag_cms_pag_77e9c7_idx_cms_cmspage_cms_pag_b83cf0_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmspage",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cms_pages",
                to="api.site",
            ),
        ),
        migrations.AlterField(
            model_name="cmspage",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
        migrations.RunPython(backfill_cms_page_site, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cmspage",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cms_pages",
                to="api.site",
            ),
        ),
        migrations.AddConstraint(
            model_name="cmspage",
            constraint=models.UniqueConstraint(
                fields=("site", "slug"), name="uniq_cms_page_site_slug"
            ),
        ),
    ]
