# Generated by Django 5.2.9 on 2026-01-14 16:53

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_siteconfig_neopay_and_legal"),
        ("cms", "0006_cmspage_site_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmspage",
            name="site",
            field=models.ForeignKey(
                default=api.models.get_default_site_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cms_pages",
                to="api.site",
            ),
        ),
    ]
