# Generated by Cascade on 2026-01-15

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_siteconfig_frontend_routes"),
        ("catalog", "0024_backinstocksubscription_site"),
        ("cms", "0007_alter_cmspage_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteNavigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        default=api.models.get_default_site_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="navigations",
                        to="api.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("url", "URL"),
                            ("category", "Category"),
                            ("brand", "Brand"),
                            ("cms_page", "CMS page"),
                        ],
                        default="url",
                        max_length=16,
                    ),
                ),
                ("url", models.URLField(blank=True, default="")),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="navigation_items",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="navigation_items",
                        to="catalog.category",
                    ),
                ),
                (
                    "cms_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="navigation_items",
                        to="cms.cmspage",
                    ),
                ),
                (
                    "navigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cms.sitenavigation",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.navigationitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="NavigationItemTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=8)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cms.navigationitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "language_code")},
            },
        ),
        migrations.AddIndex(
            model_name="navigationitem",
            index=models.Index(
                fields=["navigation", "parent", "sort_order", "id"],
                name="cms_navite_navigat_4d9621_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="navigationitem",
            index=models.Index(
                fields=["navigation", "is_active"],
                name="cms_navite_navigat_5e2a2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="navigationitemtranslation",
            index=models.Index(
                fields=["item", "language_code"],
                name="cms_navit_item_id_799a2b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitenavigation",
            constraint=models.UniqueConstraint(
                fields=("site", "code"),
                name="uniq_sitenav_site_code",
            ),
        ),
    ]
