# Generated by Cascade on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_navigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationitem",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cms/navigation/"),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="navigationitemtranslation",
            name="badge",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="navigationitemtranslation",
            name="badge_kind",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
