# Generated by Django 5.2.9 on 2026-01-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_navigation_item_media_badges"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="navigationitem",
            new_name="cms_navigat_navigat_44343d_idx",
            old_name="cms_navite_navigat_4d9621_idx",
        ),
        migrations.RenameIndex(
            model_name="navigationitem",
            new_name="cms_navigat_navigat_7e6589_idx",
            old_name="cms_navite_navigat_5e2a2b_idx",
        ),
        migrations.RenameIndex(
            model_name="navigationitemtranslation",
            new_name="cms_navigat_item_id_f62efb_idx",
            old_name="cms_navit_item_id_799a2b_idx",
        ),
    ]
