# Generated by Django 5.2.9 on 2026-01-14

from django.db import migrations, models


def create_default_site(apps, schema_editor):
    Site = apps.get_model("api", "Site")
    Site.objects.get_or_create(
        code="default",
        defaults={
            "primary_domain": "",
            "default_language_code": "",
            "default_country_code": "",
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=50, unique=True)),
                ("primary_domain", models.CharField(blank=True, default="", max_length=255)),
                ("default_language_code", models.CharField(blank=True, default="", max_length=8)),
                ("default_country_code", models.CharField(blank=True, default="", max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.RunPython(
            code=create_default_site,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
