# Generated by Django 5.2.9 on 2026-01-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_site_configs(apps, schema_editor):
    Site = apps.get_model("api", "Site")
    SiteConfig = apps.get_model("api", "SiteConfig")

    default_from = getattr(settings, "DEFAULT_FROM_EMAIL", "") or ""
    host = getattr(settings, "EMAIL_HOST", "") or ""
    port = int(getattr(settings, "EMAIL_PORT", 587) or 587)
    user = getattr(settings, "EMAIL_HOST_USER", "") or ""
    password = getattr(settings, "EMAIL_HOST_PASSWORD", "") or ""
    use_tls = bool(getattr(settings, "EMAIL_USE_TLS", True))
    use_ssl = bool(getattr(settings, "EMAIL_USE_SSL", False))
    timeout = int(getattr(settings, "EMAIL_TIMEOUT", 10) or 10)

    for s in Site.objects.all().only("id"):
        SiteConfig.objects.get_or_create(
            site_id=int(s.id),
            defaults={
                "default_from_email": default_from,
                "smtp_host": host,
                "smtp_port": port,
                "smtp_user": user,
                "smtp_password": password,
                "smtp_use_tls": use_tls,
                "smtp_use_ssl": use_ssl,
                "smtp_timeout": timeout,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_from_email", models.CharField(blank=True, default="", max_length=255)),
                ("smtp_host", models.CharField(blank=True, default="", max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_user", models.CharField(blank=True, default="", max_length=255)),
                ("smtp_password", models.CharField(blank=True, default="", max_length=255)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("smtp_use_ssl", models.BooleanField(default=False)),
                ("smtp_timeout", models.PositiveIntegerField(default=10)),
                ("terms_url", models.URLField(blank=True, default="")),
                ("privacy_url", models.URLField(blank=True, default="")),
                ("terms_version", models.CharField(blank=True, default="", max_length=50)),
                ("privacy_version", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="api.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site__code"],
            },
        ),
        migrations.RunPython(code=create_site_configs, reverse_code=migrations.RunPython.noop),
    ]
