# Generated by Django 5.2.9 on 2026-01-14

from django.conf import settings
from django.db import migrations, models


def backfill_siteconfig_fields(apps, schema_editor):
    SiteConfig = apps.get_model("api", "SiteConfig")

    # Legal/consents defaults from settings
    terms_url = getattr(settings, "CHECKOUT_TERMS_URL", "") or ""
    privacy_url = getattr(settings, "CHECKOUT_PRIVACY_URL", "") or ""
    terms_ver = getattr(settings, "CHECKOUT_TERMS_VERSION", "") or ""
    privacy_ver = getattr(settings, "CHECKOUT_PRIVACY_VERSION", "") or ""

    # Neopay defaults from existing DB config (global), if present
    neopay_project_id = None
    neopay_project_key = ""
    neopay_client_redirect_url = ""
    neopay_enable_bank_preselect = False

    try:
        NeopayConfig = apps.get_model("payments", "NeopayConfig")
        cfg = NeopayConfig.objects.filter(is_active=True).order_by("-id").first()
        if cfg is not None:
            neopay_project_id = int(getattr(cfg, "project_id", 0) or 0) or None
            neopay_project_key = str(getattr(cfg, "project_key", "") or "").strip()
            neopay_client_redirect_url = str(getattr(cfg, "client_redirect_url", "") or "").strip()
            neopay_enable_bank_preselect = bool(getattr(cfg, "enable_bank_preselect", False))
    except Exception:
        # Keep defaults
        pass

    for sc in SiteConfig.objects.all().only("id"):
        updates = {}
        # Only backfill empty values to avoid overriding manual per-site config.
        if not (getattr(sc, "terms_url", "") or "").strip() and terms_url:
            updates["terms_url"] = terms_url
        if not (getattr(sc, "privacy_url", "") or "").strip() and privacy_url:
            updates["privacy_url"] = privacy_url
        if not (getattr(sc, "terms_version", "") or "").strip() and terms_ver:
            updates["terms_version"] = terms_ver
        if not (getattr(sc, "privacy_version", "") or "").strip() and privacy_ver:
            updates["privacy_version"] = privacy_ver

        if getattr(sc, "neopay_project_id", None) is None and neopay_project_id is not None:
            updates["neopay_project_id"] = neopay_project_id
        if not (getattr(sc, "neopay_project_key", "") or "").strip() and neopay_project_key:
            updates["neopay_project_key"] = neopay_project_key
        if not (getattr(sc, "neopay_client_redirect_url", "") or "").strip() and neopay_client_redirect_url:
            updates["neopay_client_redirect_url"] = neopay_client_redirect_url
        if not bool(getattr(sc, "neopay_enable_bank_preselect", False)) and neopay_enable_bank_preselect:
            updates["neopay_enable_bank_preselect"] = neopay_enable_bank_preselect

        if updates:
            SiteConfig.objects.filter(id=sc.id).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_siteconfig"),
        ("payments", "0007_rename_payments_neop_country__96a492_idx_payments_ne_country_ccef0c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="neopay_project_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="neopay_project_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="neopay_client_redirect_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="neopay_enable_bank_preselect",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(code=backfill_siteconfig_fields, reverse_code=migrations.RunPython.noop),
    ]
