# Generated by Cascade on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_siteconfig_neopay_and_legal"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="category_path_template",
            field=models.CharField(blank=True, default="/c/{slug}", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="brand_path_template",
            field=models.CharField(blank=True, default="/b/{slug}", max_length=255),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="cms_page_path_template",
            field=models.CharField(blank=True, default="/page/{slug}", max_length=255),
        ),
    ]
