# Generated by Django 5.2.9 on 2026-01-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_siteconfig_frontend_routes"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="default_language_code",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
