# Generated by Django 5.2.9 on 2026-01-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_siteconfig_default_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="privacy_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="terms_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
