# Generated by Django 5.2.9 on 2026-01-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_siteconfig_privacy_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="default_country_code",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
