# Generated by Django 5.2.9 on 2026-01-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_consenttype_customergroup_user_customer_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergroup",
            name="allow_additional_discounts",
            field=models.BooleanField(
                default=True,
                help_text="If false, later discount engine should ignore other promotions/coupons for this group.",
            ),
        ),
        migrations.AddField(
            model_name="customergroup",
            name="pricing_type",
            field=models.CharField(
                choices=[("retail", "Retail"), ("wholesale", "Wholesale")],
                default="retail",
                max_length=16,
            ),
        ),
    ]
