# Generated by Django 5.2.9 on 2026-01-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customergroup_allow_additional_discounts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergroup",
            name="allow_coupons",
            field=models.BooleanField(
                default=True,
                help_text="If false, later discount engine should ignore coupon codes for this group.",
            ),
        ),
    ]
