# Generated by Django 5.2.9 on 2026-01-05 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customergroup_allow_coupons"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(max_length=32)),
                ("country_code", models.CharField(default="LT", max_length=2)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("is_default_shipping", models.BooleanField(default=False)),
                ("is_default_billing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-is_default_shipping",
                    "-is_default_billing",
                    "-updated_at",
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "country_code"],
                        name="accounts_us_user_id_8a93d6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default_shipping", True)),
                        fields=("user",),
                        name="uniq_default_shipping_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default_billing", True)),
                        fields=("user",),
                        name="uniq_default_billing_per_user",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Prefer E.164 format, e.g. +3706... ", max_length=32
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "phone"],
                "indexes": [
                    models.Index(
                        fields=["user", "phone"], name="accounts_us_user_id_545ac4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "phone"), name="uniq_user_phone"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("user",),
                        name="uniq_primary_phone_per_user",
                    ),
                ],
            },
        ),
    ]
