# Generated by Django 5.2.9 on 2026-01-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_useraddress_userphone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="line2",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="region",
        ),
        migrations.AddField(
            model_name="useraddress",
            name="company_reg_no",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="company_vat_no",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
