# Generated by Django 5.2.9 on 2026-01-12

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_useraddress_line2_remove_useraddress_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_method_code", models.SlugField(max_length=50)),
                ("pickup_point_id", models.CharField(max_length=80)),
                ("pickup_point_name", models.CharField(blank=True, default="", max_length=255)),
                ("pickup_point_raw", models.JSONField(blank=True, default=dict)),
                ("country_code", models.CharField(blank=True, default="", max_length=2)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_pickup_point",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "shipping_method_code"], name="accounts_us_user_id_1d5f99_idx")],
            },
        ),
    ]
