# Generated by Django 5.2.9 on 2026-01-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_userpickuppoint"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userpickuppoint",
            new_name="accounts_us_user_id_d6a5f1_idx",
            old_name="accounts_us_user_id_1d5f99_idx",
        ),
    ]
