# Generated by Django 5.2.9 on 2026-01-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unisend", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="unisendterminal",
            new_name="unisend_uni_country_83fd41_idx",
            old_name="unisend_ter_country_5bd6f0_idx",
        ),
        migrations.RenameIndex(
            model_name="unisendterminal",
            new_name="unisend_uni_termina_f73de2_idx",
            old_name="unisend_ter_terminal_2d1c35_idx",
        ),
    ]
