# Generated by Django 5.2.9 on 2026-01-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("terms", "Terms of sale"),
                            ("privacy", "Privacy notice"),
                        ],
                        max_length=32,
                    ),
                ),
                ("document_version", models.CharField(max_length=80)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="checkout.order",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-accepted_at"],
                        name="checkout_or_kind_769af9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "kind"), name="uniq_order_consent_kind"
                    )
                ],
            },
        ),
    ]
