# Generated by Django 5.2.9 on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_order_carrier_code_order_delivery_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_net_manual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
