# Generated by Django 5.2.9 on 2026-01-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_order_shipping_net_manual"),
        ("dpd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_locker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="dpd.dpdlocker",
            ),
        ),
    ]
