# Generated by Django 5.2.9 on 2026-01-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0007_cart_guest_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentintent",
            name="provider",
            field=models.CharField(
                choices=[
                    ("klix", "Klix (Citadele)"),
                    ("bank_transfer", "Bank transfer"),
                ],
                default="klix",
                max_length=20,
            ),
        ),
    ]
