# Generated by Django 5.2.9 on 2026-01-08 07:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0011_variant_height_cm_variant_length_cm_variant_weight_g_and_more",
        ),
        ("checkout", "0008_alter_paymentintent_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                (
                    "min_items_gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_items_gross",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "payment_method_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("amount_net", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_rules",
                        to="catalog.taxclass",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="OrderFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=200)),
                ("net", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=5, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("vat", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="checkout.order",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_fees",
                        to="checkout.feerule",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="feerule",
            index=models.Index(
                fields=["is_active", "country_code", "sort_order"],
                name="checkout_fe_is_acti_747726_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feerule",
            index=models.Index(
                fields=["payment_method_code"], name="checkout_fe_payment_27726c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderfee",
            index=models.Index(
                fields=["order", "code"], name="checkout_or_order_i_b4cc50_idx"
            ),
        ),
    ]
