# Generated by Django 5.2.9 on 2026-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0010_alter_paymentintent_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="neopay_bank_bic",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="neopay_bank_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
