# Generated by Django 5.2.9 on 2026-01-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0011_paymentintent_neopay_bank_bic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentintent",
            name="redirect_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
    ]
