# Generated by Django 5.2.9 on 2026-01-08 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0012_alter_paymentintent_redirect_url"),
        ("dpd", "0002_dpdconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fulfillment", "Fulfillment"),
                            ("delivery", "Delivery"),
                            ("payment", "Payment"),
                            ("note", "Note"),
                        ],
                        default="note",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=80)),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_mode",
            field=models.CharField(
                choices=[
                    ("stock", "Stock"),
                    ("dropship", "Dropship"),
                    ("mixed", "Mixed"),
                ],
                default="stock",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier_reservation_status",
            field=models.CharField(
                choices=[
                    ("not_needed", "Not needed"),
                    ("pending", "Pending"),
                    ("reserved", "Reserved"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_needed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier_reserved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=[
                    "fulfillment_mode",
                    "supplier_reservation_status",
                    "-created_at",
                ],
                name="checkout_or_fulfill_a01176_idx",
            ),
        ),
        migrations.AddField(
            model_name="orderevent",
            name="actor_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderevent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="checkout.order",
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["order", "-created_at"], name="checkout_or_order_i_185aca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["kind", "-created_at"], name="checkout_or_kind_ce1b9d_idx"
            ),
        ),
    ]
