# Generated by Django 5.2.9 on 2026-01-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0011_variant_height_cm_variant_length_cm_variant_weight_g_and_more",
        ),
        ("checkout", "0013_orderevent_order_fulfillment_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("captured", "Captured"),
                            ("released", "Released"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="catalog.inventoryitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_allocations",
                        to="checkout.order",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_allocations",
                        to="checkout.orderline",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["order", "status", "-created_at"],
                        name="checkout_in_order_i_17b8e9_idx",
                    ),
                    models.Index(
                        fields=["inventory_item", "status"],
                        name="checkout_in_invento_5d95f4_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("qty__gte", 0)), name="chk_alloc_qty_gte_0"
                    )
                ],
            },
        ),
    ]
