# Generated by Django 5.2.9 on 2026-01-09

from __future__ import annotations

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0015_cartitem_orderline_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("coupon", "Coupon"), ("promo", "Promo")],
                        default="coupon",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=80)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "net",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="discounts",
                        to="checkout.order",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="orderdiscount",
            index=models.Index(fields=["order", "kind"], name="checkout_or_order_i_3f8b8d_idx"),
        ),
        migrations.AddIndex(
            model_name="orderdiscount",
            index=models.Index(fields=["kind", "code"], name="checkout_or_kind_co_0b5fcb_idx"),
        ),
    ]
