# Generated by Django 5.2.9 on 2026-01-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0016_orderdiscount"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orderdiscount",
            new_name="checkout_or_order_i_249c73_idx",
            old_name="checkout_or_order_i_3f8b8d_idx",
        ),
        migrations.RenameIndex(
            model_name="orderdiscount",
            new_name="checkout_or_kind_111258_idx",
            old_name="checkout_or_kind_co_0b5fcb_idx",
        ),
    ]
