# Generated by Django 5.2.9 on 2026-01-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0018_order_delivery_eta_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(default="unisend_pickup", max_length=50),
        ),
    ]
