# Generated by Django 5.2.9 on 2026-01-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0021_feerule_site_scope"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feerule",
            name="checkout_fe_is_acti_747726_idx",
        ),
        migrations.RemoveIndex(
            model_name="feerule",
            name="checkout_fe_payment_27726c_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="checkout_or_user_id_5f4304_idx",
        ),
        migrations.RenameIndex(
            model_name="feerule",
            new_name="checkout_fe_site_id_667ec9_idx",
            old_name="checkout_fe_site_i_3cc8b1_idx",
        ),
        migrations.RenameIndex(
            model_name="feerule",
            new_name="checkout_fe_site_id_d5d0c6_idx",
            old_name="checkout_fe_site_p_58d2a3_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="checkout_or_site_id_196da9_idx",
            old_name="checkout_or_site_user_ca_idx",
        ),
    ]
