# Generated by Django 5.2.9 on 2026-01-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homebuilder", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="heroslidetranslation",
            new_name="homebuilder_hero_sl_f30c9b_idx",
            old_name="homebuilder_h_hero_sl_0c9c5b_idx",
        ),
        migrations.RenameIndex(
            model_name="homepagetranslation",
            new_name="homebuilder_home_pa_04602e_idx",
            old_name="homebuilder_h_home_pa_5f8cb6_idx",
        ),
        migrations.RenameIndex(
            model_name="homesectiontranslation",
            new_name="homebuilder_home_se_a6a815_idx",
            old_name="homebuilder_h_home_se_1657aa_idx",
        ),
        migrations.RenameIndex(
            model_name="newslettersectiontranslation",
            new_name="homebuilder_newslet_7b4c8f_idx",
            old_name="homebuilder_h_news_le_43e0c9_idx",
        ),
        migrations.RenameIndex(
            model_name="richtextsectiontranslation",
            new_name="homebuilder_rich_te_bf4802_idx",
            old_name="homebuilder_h_rich_te_1bcb08_idx",
        ),
    ]
