# Generated by Django 5.2.9 on 2026-01-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_default_variants"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("country_code", models.CharField(max_length=2)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("dispatch_days_min", models.PositiveSmallIntegerField(default=0)),
                ("dispatch_days_max", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_on_hand", models.IntegerField(default=0)),
                ("qty_reserved", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="catalog.variant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="catalog.warehouse",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("variant", "warehouse"),
                        name="uniq_inventory_item_variant_warehouse",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("qty_on_hand__gte", 0)),
                        name="chk_inventory_qty_on_hand_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("qty_reserved__gte", 0)),
                        name="chk_inventory_qty_reserved_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("qty_reserved__lte", models.F("qty_on_hand"))
                        ),
                        name="chk_inventory_qty_reserved_lte_on_hand",
                    ),
                ],
            },
        ),
    ]
