# Generated by Django 5.2.9 on 2026-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_warehouse_inventoryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="cost_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional per-warehouse purchase cost override.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="cost_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Purchase cost (net) for margin/discount floor checks.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cost_eur__gte", 0), ("cost_eur__isnull", True), _connector="OR"
                ),
                name="chk_inventory_cost_eur_gte_0",
            ),
        ),
    ]
