# Generated by Django 5.2.9 on 2026-01-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_inventoryitem_cost_eur_variant_cost_eur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product-images/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
