# Generated by Django 5.2.9 on 2026-01-05 14:05

import django.db.models.deletion
from django.db import migrations, models


def seed_standard_tax_class(apps, schema_editor):
    TaxClass = apps.get_model("catalog", "TaxClass")
    Product = apps.get_model("catalog", "Product")

    standard, _ = TaxClass.objects.get_or_create(
        code="standard",
        defaults={"name": "Standard VAT", "is_active": True, "sort_order": 0},
    )

    Product.objects.filter(tax_class__isnull=True).update(tax_class=standard)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productimage_image_alter_productimage_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tax_class",
            field=models.ForeignKey(
                blank=True,
                help_text="VAT class used to calculate gross/VAT for destination country.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.taxclass",
            ),
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("rate", models.DecimalField(decimal_places=5, max_digits=6)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tax_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="catalog.taxclass",
                    ),
                ),
            ],
            options={
                "ordering": ["country_code", "tax_class__code", "-valid_from"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tax_class", "country_code", "valid_from"),
                        name="uniq_tax_rate_effective",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate__gte", 0), ("rate__lte", 1)),
                        name="chk_tax_rate_between_0_and_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_to__gte", models.F("valid_from")),
                            ("valid_to__isnull", True),
                            _connector="OR",
                        ),
                        name="chk_tax_rate_valid_to_gte_valid_from",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_standard_tax_class,
                             migrations.RunPython.noop),
    ]
