# Generated by Django 5.2.9 on 2026-01-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_taxclass_product_tax_class_taxrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, help_text="Markdown (rekomenduojama)."),
        ),
        migrations.AddField(
            model_name="category",
            name="hero_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category-hero/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="hero_image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="hero_image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="category",
            name="menu_icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="category-icons/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="menu_icon_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="menu_icon_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_description",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
