# Generated by Django 5.2.9 on 2026-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_category_description_category_hero_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_avif",
            field=models.ImageField(
                blank=True, null=True, upload_to="product-images/derived/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_webp",
            field=models.ImageField(
                blank=True, null=True, upload_to="product-images/derived/%Y/%m/"
            ),
        ),
    ]
