# Generated by Django 5.2.9 on 2026-01-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_productimage_image_avif_productimage_image_webp"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="listing_avif",
            field=models.ImageField(
                blank=True, null=True, upload_to="product-images/derived/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="listing_webp",
            field=models.ImageField(
                blank=True, null=True, upload_to="product-images/derived/%Y/%m/"
            ),
        ),
    ]
