# Generated by Django 5.2.9 on 2026-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_productimage_listing_avif_productimage_listing_webp"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="height_cm",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="variant",
            name="length_cm",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="variant",
            name="weight_g",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="variant",
            name="width_cm",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
