# Generated by Django 5.2.9 on 2026-01-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_remove_product_stock_qty_remove_variant_stock_qty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_eur",
        ),
    ]
