# Generated by Django 5.2.9 on 2026-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_inventoryitem_never_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiontype",
            name="display_type",
            field=models.CharField(
                choices=[
                    ("select", "Select"),
                    ("radio", "Radio"),
                    ("swatch", "Swatch"),
                ],
                default="radio",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="optiontype",
            name="swatch_type",
            field=models.CharField(
                blank=True,
                choices=[("hex", "Hex"), ("name", "Name"), ("image", "Image")],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
