# Generated by Django 5.2.9 on 2026-01-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_optiontype_display_type_optiontype_swatch_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackInStockSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "channel",
                    models.CharField(
                        choices=[("normal", "Normal"), ("outlet", "Outlet")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="back_in_stock_subscriptions",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="back_in_stock_subscriptions",
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "product", "variant", "channel"),
                        name="uniq_back_in_stock_subscription",
                    )
                ],
            },
        ),
    ]
