# Generated by Django 5.2.9 on 2026-01-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_backinstocksubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rich_text", "Rich text"),
                            ("table", "Table"),
                            ("image", "Image"),
                            ("callout", "Callout"),
                            ("accordion", "Accordion"),
                            ("attachments", "Attachments"),
                        ],
                        default="rich_text",
                        max_length=32,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("product_detail", "Product detail"),
                            ("cart", "Cart"),
                            ("checkout", "Checkout"),
                            ("order_confirmation", "Order confirmation"),
                            ("global", "Global"),
                        ],
                        default="product_detail",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "key"],
            },
        ),
        migrations.CreateModel(
            name="ContentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("is_exclusive", models.BooleanField(default=False)),
                ("channel", models.CharField(blank=True, default="", max_length=16)),
                ("include_descendants", models.BooleanField(default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_rules",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_rules",
                        to="catalog.category",
                    ),
                ),
                (
                    "content_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="catalog.contentblock",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_rules",
                        to="catalog.product",
                    ),
                ),
                (
                    "product_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_rules",
                        to="catalog.productgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlockTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("markdown", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "content_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.contentblock",
                    ),
                ),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name="contentblocktranslation",
            constraint=models.UniqueConstraint(
                fields=("content_block", "language_code"),
                name="uniq_content_block_translation",
            ),
        ),
    ]
