# Generated by Django 5.2.9 on 2026-01-12

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_content_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="backinstocksubscription",
            name="language_code",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
