# Generated by Django 5.2.9 on 2026-01-14 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_backinstocksubscription_language_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "matcher_type",
                    models.CharField(
                        choices=[("contains", "Contains"), ("regex", "Regex")],
                        default="contains",
                        max_length=20,
                    ),
                ),
                ("pattern", models.CharField(blank=True, default="", max_length=500)),
                ("extract_group", models.PositiveSmallIntegerField(default=0)),
                (
                    "value_template",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "fixed_value",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "value_format",
                    models.CharField(
                        choices=[("raw", "Raw"), ("decimal_trim", "Decimal trim")],
                        default="raw",
                        max_length=20,
                    ),
                ),
                ("match_in_name", models.BooleanField(default=True)),
                ("match_in_description", models.BooleanField(default=True)),
                ("match_in_sku", models.BooleanField(default=False)),
                ("include_descendants", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrichment_rules",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrichment_rules",
                        to="catalog.category",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrichment_rules",
                        to="catalog.feature",
                    ),
                ),
                (
                    "product_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrichment_rules",
                        to="catalog.productgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="EnrichmentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("dry_run", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrichment_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="EnrichmentMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_field",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "matched_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "extracted_value",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("skipped_exists", "Skipped (exists)"),
                            ("skipped_conflict", "Skipped (conflict)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_matches",
                        to="catalog.product",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="catalog.enrichmentrule",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="catalog.enrichmentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
