# Generated by Django 5.2.9 on 2026-01-14

import django.db.models.deletion
from django.db import migrations, models


def backfill_content_block_site(apps, schema_editor):
    Site = apps.get_model("api", "Site")
    ContentBlock = apps.get_model("catalog", "ContentBlock")

    site = Site.objects.filter(is_active=True, code="default").only("id").first()
    if site is None:
        site = Site.objects.filter(is_active=True).only("id").order_by("code").first()
    if site is None:
        return

    ContentBlock.objects.filter(site__isnull=True).update(site_id=int(site.id))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("catalog", "0020_enrichmentrule_enrichmentrun_enrichmentmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentblock",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_blocks",
                to="api.site",
            ),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="key",
            field=models.SlugField(max_length=100),
        ),
        migrations.RunPython(backfill_content_block_site, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="contentblock",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_blocks",
                to="api.site",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentblock",
            constraint=models.UniqueConstraint(
                fields=("site", "key"), name="uniq_content_block_site_key"
            ),
        ),
    ]
