# Generated by Django 5.2.9 on 2026-01-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("catalog", "0021_contentblock_site_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBrandExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_exclusion_rules",
                        to="catalog.brand",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_brands",
                        to="api.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteCategoryVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("include_descendants", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_visibility_rules",
                        to="catalog.category",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visible_categories",
                        to="api.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteCategoryBrandExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("include_descendants", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_category_exclusion_rules",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_brand_exclusions",
                        to="catalog.category",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_category_brands",
                        to="api.site",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="sitecategoryvisibility",
            constraint=models.UniqueConstraint(
                fields=("site", "category"), name="uniq_site_category_visibility"
            ),
        ),
        migrations.AddConstraint(
            model_name="sitebrandexclusion",
            constraint=models.UniqueConstraint(
                fields=("site", "brand"), name="uniq_site_brand_exclusion"
            ),
        ),
        migrations.AddConstraint(
            model_name="sitecategorybrandexclusion",
            constraint=models.UniqueConstraint(
                fields=("site", "category", "brand"), name="uniq_site_category_brand_exclusion"
            ),
        ),
    ]
