# Generated by Django 5.2.9 on 2026-01-14

from django.db import migrations, models
import django.db.models.deletion


def backfill_back_in_stock_site(apps, schema_editor):
    Site = apps.get_model("api", "Site")
    BackInStockSubscription = apps.get_model("catalog", "BackInStockSubscription")

    default_site = Site.objects.filter(is_active=True, code="default").only("id").first()
    if default_site is None:
        default_site = Site.objects.filter(is_active=True).only("id").order_by("code").first()
    if default_site is None:
        return

    BackInStockSubscription.objects.filter(site_id__isnull=True).update(site_id=int(default_site.id))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_siteconfig_neopay_and_legal"),
        ("catalog", "0023_alter_contentblock_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="backinstocksubscription",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="back_in_stock_subscriptions",
                to="api.site",
            ),
        ),
        migrations.RunPython(code=backfill_back_in_stock_site, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="backinstocksubscription",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="back_in_stock_subscriptions",
                to="api.site",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="backinstocksubscription",
            name="uniq_back_in_stock_subscription",
        ),
        migrations.AddConstraint(
            model_name="backinstocksubscription",
            constraint=models.UniqueConstraint(
                fields=("site", "email", "product", "variant", "channel"),
                name="uniq_back_in_stock_subscription",
            ),
        ),
    ]
