# Generated by Django 5.2.9 on 2026-01-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_rebuild_category_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="brand-logos/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="logo_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="brand",
            name="logo_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="brand",
            name="seo_description",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="brand",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="brand",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="BrandTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "seo_description",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                (
                    "seo_keywords",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "language_code"), name="uniq_brand_translation"
                    ),
                    models.UniqueConstraint(
                        fields=("language_code", "slug"),
                        name="uniq_brand_translation_slug",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "seo_description",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                (
                    "seo_keywords",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "language_code"),
                        name="uniq_category_translation",
                    ),
                    models.UniqueConstraint(
                        fields=("language_code", "slug"),
                        name="uniq_category_translation_slug",
                    ),
                ],
            },
        ),
    ]
