# Generated by Django 5.2.9 on 2026-01-16 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_brand_description_brand_logo_brand_logo_alt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productgroup",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="FeatureTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.feature",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feature", "language_code"),
                        name="uniq_feature_translation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeatureValueTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("value", models.CharField(blank=True, default="", max_length=255)),
                (
                    "feature_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.featurevalue",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feature_value", "language_code"),
                        name="uniq_feature_value_translation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OptionTypeTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "option_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.optiontype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("option_type", "language_code"),
                        name="uniq_option_type_translation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OptionValueTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "option_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.optionvalue",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("option_value", "language_code"),
                        name="uniq_option_value_translation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductGroupTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "seo_description",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                (
                    "seo_keywords",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "product_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.productgroup",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_group", "language_code"),
                        name="uniq_product_group_translation",
                    ),
                    models.UniqueConstraint(
                        fields=("language_code", "slug"),
                        name="uniq_product_group_translation_slug",
                    ),
                ],
            },
        ),
    ]
