# Generated by Django 5.2.9 on 2026-01-16 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_productgroup_slug_featuretranslation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "seo_description",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                (
                    "seo_keywords",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "language_code"),
                        name="uniq_product_translation",
                    ),
                    models.UniqueConstraint(
                        fields=("language_code", "slug"),
                        name="uniq_product_translation_slug",
                    ),
                ],
            },
        ),
    ]
