# Generated by Django 5.2.9 on 2026-01-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_backinstocksubscription"),
        ("shipping", "0003_add_lpexpress_courier"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[("lead_time", "Lead time"), ("cycle", "Cycle")],
                        default="lead_time",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("timezone", models.CharField(default="Europe/Vilnius", max_length=64)),
                ("channel", models.CharField(blank=True, default="", max_length=20)),
                (
                    "processing_business_days_min",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "processing_business_days_max",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "shipping_business_days_min",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "shipping_business_days_max",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("cutoff_time", models.TimeField(blank=True, null=True)),
                (
                    "order_window_start_weekday",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("order_window_start_time", models.TimeField(blank=True, null=True)),
                (
                    "order_window_end_weekday",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("order_window_end_time", models.TimeField(blank=True, null=True)),
                (
                    "supplier_inbound_business_days_min",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "supplier_inbound_business_days_max",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "warehouse_pack_business_days_min",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "warehouse_pack_business_days_max",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "carrier_business_days_min",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "carrier_business_days_max",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_rules",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_rules",
                        to="catalog.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_rules",
                        to="catalog.product",
                    ),
                ),
                (
                    "product_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_rules",
                        to="catalog.productgroup",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_rules",
                        to="catalog.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "code"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("country_code", models.CharField(default="LT", max_length=2)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["country_code", "date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "date"),
                        name="uniq_holiday_country_date",
                    )
                ],
            },
        ),
    ]
