# Generated by Django 5.2.9 on 2026-01-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0007_shippingmethod_image"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="shippingcountrytranslation",
            new_name="shipping_sh_shippin_a2d220_idx",
            old_name="shipping_shi_shipping_21fe3e_idx",
        ),
    ]
