# Generated by Cascade on 2026-01-15

import api.models
import django.db.models.deletion
from django.db import migrations, models


def backfill_deliveryrule_site(apps, schema_editor):
    DeliveryRule = apps.get_model("shipping", "DeliveryRule")
    default_site_id = api.models.get_default_site_id()
    try:
        default_site_id = int(default_site_id)
    except Exception:
        default_site_id = 1

    # Only backfill rows that have null/zero (should not happen if default applied, but keep safe).
    try:
        DeliveryRule.objects.filter(site_id__isnull=True).update(site_id=default_site_id)
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_siteconfig_frontend_routes"),
        ("shipping", "0008_rename_shipping_shi_shipping_21fe3e_idx_shipping_sh_shippin_a2d220_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="allowed_sites",
            field=models.ManyToManyField(blank=True, related_name="shipping_methods", to="api.site"),
        ),
        migrations.AddField(
            model_name="deliveryrule",
            name="site",
            field=models.ForeignKey(
                default=api.models.get_default_site_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_rules",
                to="api.site",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrule",
            name="code",
            field=models.SlugField(max_length=100),
        ),
        migrations.RunPython(code=backfill_deliveryrule_site, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="deliveryrule",
            constraint=models.UniqueConstraint(fields=("site", "code"), name="uniq_deliveryrule_site_code"),
        ),
    ]
