# Generated by Django 5.2.9 on 2026-01-12

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_seed_catalog_back_in_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="key",
            field=models.SlugField(max_length=100),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="language_code",
            field=models.CharField(default="lt", max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("key", "language_code")},
        ),
    ]
