# Generated by Django on 2026-01-15

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0024_backinstocksubscription_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("complements", "Complements"),
                            ("upsell", "Upsell"),
                            ("similar", "Similar"),
                        ],
                        default="complements",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["kind", "is_active"], name="recommendat_kind_0d5c2c_idx"),
                    models.Index(fields=["created_at"], name="recommendat_created_8b3874_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecommendationSetItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_set_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="recommendations.recommendationset",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["set", "sort_order", "id"], name="recommendat_set_id_8e37ac_idx"),
                    models.Index(fields=["product", "id"], name="recommendat_product_b9a2c0_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recommendationsetitem",
            constraint=models.UniqueConstraint(fields=("set", "product"), name="uniq_reco_set_product"),
        ),
    ]
