# Generated by Django 5.2.9 on 2026-01-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recommendationset",
            new_name="recommendat_kind_23755c_idx",
            old_name="recommendat_kind_0d5c2c_idx",
        ),
        migrations.RenameIndex(
            model_name="recommendationset",
            new_name="recommendat_created_b61255_idx",
            old_name="recommendat_created_8b3874_idx",
        ),
        migrations.RenameIndex(
            model_name="recommendationsetitem",
            new_name="recommendat_set_id_162e27_idx",
            old_name="recommendat_set_id_8e37ac_idx",
        ),
        migrations.RenameIndex(
            model_name="recommendationsetitem",
            new_name="recommendat_product_62e7b2_idx",
            old_name="recommendat_product_b9a2c0_idx",
        ),
    ]
